### ISSUE TITLE
action type "tx"?

### ISSUE THREAD

**Issue by ackvf** [Zizzamia/a-frame-in-100-lines#12]
https://github.com/Zizzamia/a-frame-in-100-lines/blob/58df73ceeeb16f0c734849d2066839a5986cab05/app/page.tsx#L10-L14

Hi, I have not seen "tx" anywhere in the documentation, where do you get this from? Few weeks ago, I learned about the `mint` action from your example too, when it was still not documented either.

thank you

**Comment by Zizzamia** [comment]
The official doc is here https://docs.farcaster.xyz/reference/frames/spec, but at times they work on new features and they have temporary SPEC written out and shared over Farcaster.

**Comment by Zizzamia** [comment]
This is the official changelog https://docs.farcaster.xyz/reference/frames/spec#vnext-changelog which can come handy.

**Comment by Zizzamia** [comment]
Closing this, let me know if you still need help with it.
