### ISSUE TITLE
action: link is wrong?

### ISSUE THREAD

**Issue by ackvf** [Zizzamia/a-frame-in-100-lines#6]
According to the [docs](https://warpcast.notion.site/Outdated-Docs-a8a98ca76a6446508c862c670ebc4cde), it seems that only `post` and `post_redirect` is supported, but it seems that type `link` also works. Can you support this with some resources?

https://github.com/Zizzamia/a-frame-in-100-lines/blob/b94bfc6a150dbf890cc7c300766e8b350ad1e8a6/app/page.tsx#L10-L14

It also gives TS error
![image](https://github.com/Zizzamia/a-frame-in-100-lines/assets/2313018/981d97c0-5807-452e-98b3-dce6c3a0a379)

**Comment by Zizzamia** [comment]
Ciao @ackvf, the docs you are referring are Outdated.

The latest docs are https://docs.farcaster.xyz/reference/frames/spec
but i can see they didn't documentated `link` yet 🤦🏻‍♂️

**Comment by Zizzamia** [comment]
@ackvf btw, yes `link` works :) 
and you can use them with the latest version of OnchainKit.

**Comment by ackvf** [comment]
Yeah, removed the notion site like two days ago and the other docs were not updated in the meantime. Good to see they are actively working on that. Thanks for the hint with `link`, so updating the types should resolve my issue.
