### ISSUE TITLE
Neynar Api Key

### ISSUE THREAD

**Issue by ssolson** [Zizzamia/a-frame-in-100-lines#8]
Does this setup require me to have Neynar Api Key for the message validation on my server?

https://github.com/Zizzamia/a-frame-in-100-lines/blob/d5a963526f07eeb1bd275178be765d8b67db441a/app/api/frame/route.ts#L10C77-L10C95

**Comment by Zizzamia** [comment]
The `NEYNAR_ONCHAIN_KIT` is a default one you can use to try out your Frame.
But has some rate-limiting, so if your Frame is used by a lot of people, might not work occasionally.

To avoid that we advice to get your own Neynar Key.

**Comment by ssolson** [comment]
Thank You.
