### ISSUE TITLE
any way i can have 4 buttons in a single row ? 

### ISSUE THREAD

**Issue by udaiparvatha** [Zizzamia/a-frame-in-100-lines#9]
this code is great for a starter like me!  wondering if there is way for me to keep 4 buttons in one row? currently have it like this 

![Screenshot 2024-02-25 at 8 11 19 PM](https://github.com/Zizzamia/a-frame-in-100-lines/assets/63920329/60433538-ea2c-4b37-ba37-bdab1d735260)

**Comment by Zizzamia** [comment]
Yeah no sorry, that's just Farcaster doing those optimization from their side. The developer has not much control on it.
